### ISSUE TITLE
Support for NetBeans 8.2

### ISSUE THREAD

**Issue by phansson** [vaadin/netbeans-plugin#6]
NetBeans 8.2 was released in Oct 2016.

Please re-build the plugin for NB 8.2.
Make sure to update the [NetBeans Plugin site](http://plugins.netbeans.org/plugin/50531/vaadin-plug-in-for-netbeans) too.

**Comment by denis-anisimov** [comment]
Thanks a lot for the notice.
The plugin is updated for 8.2
